### PR TITLE
Restructure tests

### PR DESCRIPTION
**Pull request by ethanresnick**
Another portion of #34.

### CODE REVIEW

**Comment by carlbennettnz** [comment]
Looks like this merge has lost previous changes. The hasNonEmptyBody stuff for example

**Comment by carlbennettnz** [comment]
Yeah, it.hasBody is no longer set but is still referred to further down

**Comment by ethanresnick** [comment]
The hasBody stuff was reworked intentionally [here](https://github.com/ethanresnick/json-api/commit/19e16edfb58ee2b5f2573a9e2d1d09cb73d05050). I thought all the tests were passing, but if you see any bugs lmk!

**Comment by carlbennettnz** [comment]
Ok, in that case it's probably fine. Just checking 😊

**Pull request merged**
