### PR TITLE
204 response contentType

### PR DESCRIPTION
**Pull request by jfurie**

### CODE REVIEW

**Comment by ethanresnick** [comment]
I'm not sure what you're working on here, but I'm pretty sure a 204 response shouldn't have a Content-Type...

**Comment by jfurie** [comment]
Yeah I think I tried to set it to null but got another error. Seemed to work well with text/plain . I'll take another look and see where the null had an issue

**Comment by ethanresnick** [comment]
Yeah, the error with null is presumably because null isn't a valid media type. The way to say that a header is "null" is just not to include the header, which is what the code already does. What problem are you trying to solve here?

**Comment by jfurie** [comment]
ah interesting.. i was getting a contentType back as (application/json) when i got the 204. thats when I started looking into it. Maybe something else isn't set right.

**Comment by jfurie** [comment]
it looks like this code will always set the content type or change the status to 406
(in http-strategy/express.js)
```javascript
  sendResources(responseObject, res, next) {
    if(responseObject.headers.vary) {
      vary(res, responseObject.headers.vary);
    }

    if(!responseObject.contentType) {
      if(this.config.handleContentNegotiation) {
        res.status(406).send();
      }
      else {
        next();
      }
    }

    else {
      res.set("Content-Type", responseObject.contentType);
      res.status(responseObject.status || 200);

      if(responseObject.headers.location) {
        res.set("Location", responseObject.headers.location);
      }

      if(responseObject.body !== null) {
        res.send(new Buffer(responseObject.body)).end();
      }
      else {
        res.end();
      }
    }
  }

```

**Comment by ethanresnick** [comment]
Yeah, you're right. My mistake! I'll fix this now.

**Comment by jfurie** [comment]
Cool! btw Ive been using your library for a week now. I like it so far. Gonna keep using it. Ill let you know if any more issues crop up. Might have to add pagination soon.

**Comment by ethanresnick** [comment]
Closed by 2ee74fb

**Pull request closed without merging**
