### PR TITLE
Pagination support

### PR DESCRIPTION
**Pull request by warp**
Pagination support with params page[offset] and page[limit] count of total records is included in meta. I am happy to add new test coverage if this is a feature you are interested in accepting.

### CODE REVIEW

**Comment by dangreenisrael** [comment]
+1 on this.

**Comment by ethanresnick** [comment]
@warp Thank you for this! It's really exciting to have this feature. I will review the code soon. In the mean time, could you add some unit tests for the various functions, and integration tests for the requests this should support and reject? I'm pretty hesitant to merge this without tests, as it'll be impossible to catch regressions (and harder for me to convince myself that this is all working). The tests already in the project should offer good templates, but I'm happy to point you in the right direction if anything's unclear.

**Comment by warp** [comment]
@ethanresnick I have added a basic integration test for page[offset] and page[limit] params and the total record count in meta. Let me know if there are any other cases you would like me to test for.

**Comment by ethanresnick** [comment]
Thanks Ben! I'll take a more detailed look tomorrow. In the mean time, it looks like one of the tests is failing? Also, I think we should have tests for the interaction of pagination with sorting and filtering.

**Comment by ethanresnick** [comment]
@warp This has been merged. Thanks again for your help on this!

**Pull request merged**
